language: php

php:
  - '7.1'
  - nightly

install:
    - flags="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
    - composer install $flags

script: phpunit -c phpunit.xml --colors=auto --testdox ${@}
